spring:
  application:
    name: NetMetering
  server:
    port:
      8080
  security:
    oauth2:
      client:
        registration:
#          google:
#            client-id: Your id
#            client-secret: Your secret
#            scope:
#              - openid
#              - email
#              - profile
#              - https://www.googleapis.com/auth/user.phonenumbers.read
#              - https://www.googleapis.com/auth/user.birthday.read
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth?prompt=select_account
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.coms